//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18408.
// 
#pragma warning disable 1591

namespace HumansoftServer.WSHumansoftPublico {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSExamenesSoap", Namespace="http://tempuri.org/")]
    public partial class WSExamenes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerRespuestasCandidatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertaRegistrosEnTablasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSExamenes() {
            this.Url = global::HumansoftServer.Properties.Settings.Default.HumansoftServer_WSHumansoftPublico_WSExamenes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerRespuestasCandidatoCompletedEventHandler ObtenerRespuestasCandidatoCompleted;
        
        /// <remarks/>
        public event InsertaRegistrosEnTablasCompletedEventHandler InsertaRegistrosEnTablasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerRespuestasCandidato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerRespuestasCandidato(string cve_candidato, int cve_examen, int cve_vacante) {
            object[] results = this.Invoke("ObtenerRespuestasCandidato", new object[] {
                        cve_candidato,
                        cve_examen,
                        cve_vacante});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerRespuestasCandidatoAsync(string cve_candidato, int cve_examen, int cve_vacante) {
            this.ObtenerRespuestasCandidatoAsync(cve_candidato, cve_examen, cve_vacante, null);
        }
        
        /// <remarks/>
        public void ObtenerRespuestasCandidatoAsync(string cve_candidato, int cve_examen, int cve_vacante, object userState) {
            if ((this.ObtenerRespuestasCandidatoOperationCompleted == null)) {
                this.ObtenerRespuestasCandidatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerRespuestasCandidatoOperationCompleted);
            }
            this.InvokeAsync("ObtenerRespuestasCandidato", new object[] {
                        cve_candidato,
                        cve_examen,
                        cve_vacante}, this.ObtenerRespuestasCandidatoOperationCompleted, userState);
        }
        
        private void OnObtenerRespuestasCandidatoOperationCompleted(object arg) {
            if ((this.ObtenerRespuestasCandidatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerRespuestasCandidatoCompleted(this, new ObtenerRespuestasCandidatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertaRegistrosEnTablas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] InsertaRegistrosEnTablas(System.Data.DataSet dsTablas) {
            object[] results = this.Invoke("InsertaRegistrosEnTablas", new object[] {
                        dsTablas});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void InsertaRegistrosEnTablasAsync(System.Data.DataSet dsTablas) {
            this.InsertaRegistrosEnTablasAsync(dsTablas, null);
        }
        
        /// <remarks/>
        public void InsertaRegistrosEnTablasAsync(System.Data.DataSet dsTablas, object userState) {
            if ((this.InsertaRegistrosEnTablasOperationCompleted == null)) {
                this.InsertaRegistrosEnTablasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertaRegistrosEnTablasOperationCompleted);
            }
            this.InvokeAsync("InsertaRegistrosEnTablas", new object[] {
                        dsTablas}, this.InsertaRegistrosEnTablasOperationCompleted, userState);
        }
        
        private void OnInsertaRegistrosEnTablasOperationCompleted(object arg) {
            if ((this.InsertaRegistrosEnTablasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertaRegistrosEnTablasCompleted(this, new InsertaRegistrosEnTablasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerRespuestasCandidatoCompletedEventHandler(object sender, ObtenerRespuestasCandidatoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerRespuestasCandidatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerRespuestasCandidatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InsertaRegistrosEnTablasCompletedEventHandler(object sender, InsertaRegistrosEnTablasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertaRegistrosEnTablasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertaRegistrosEnTablasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591